import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {auth} from "@/auth"
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/providers/theme-providers";
import {SessionProvider} from "next-auth/react"
import { Toaster } from "sonner";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const session=await auth()
    console.log("SESSION:",session)
  return (

    
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
      <body className="min-h-full flex flex-col">
         <SessionProvider session={session}>
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>
                <TooltipProvider>
                  <Toaster/>
                  <div className="flex flex-col min-h-screen">
                    <div className="flex-1">
                    {children}
                    </div>
                  </div>
                
                </TooltipProvider>
            </ThemeProvider>     
          </SessionProvider>
        </body>
    </html>
    
  );
}
